### ISSUE TITLE
Equation in tutorial example ipynb not correct

### ISSUE THREAD

**Issue by xiaolongwu0713** [Eden-Kramer-Lab/spectral_connectivity#26]
Hi,
The equation in Baccala Example 2 now is x_1=0.5*x_1(n-1)+0.3*x_2(n-1)+0.4*x_3x(n-1)+w_1(n). There is an extra x in the equation. Should it be x_1=0.5*x_1(n-1)+0.3*x_2(n-1)+0.4*x_3(n-1)+w_1(n)?
It is confusing for beginners.

**Comment by edeno** [comment]
Hi @xiaolongwu0713 ,

Thanks for catching this. I will change this in the notebooks.
