### ISSUE TITLE
[JOSS] Extend CONTRIBUTING.md and add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by sappelhoff** [Eden-Kramer-Lab/spectral_connectivity#36]
I recommend that you extend your contributor guidelines, they could additionally contain:

- how to build docs
- how to make a release (or at least, what the processes are -- especially given that you use both pypi and conda)

Next to that I recommend that you include a code of conduct file, for example following: https://www.contributor-covenant.org/

xref: https://github.com/openjournals/joss-reviews/issues/4840

**Comment by edeno** [comment]
@sappelhoff 16d8f9c024de9ab1c4b219049306e90911322f36 and 9a0e5ed2d001f5a4c4f5dbf6de93aacd74e3f51f should address this issue.
