### ISSUE TITLE
[JOSS] Axes for expectation`time_trials_tapers`

### ISSUE THREAD

**Issue by EtienneCmb** [Eden-Kramer-Lab/spectral_connectivity#44]
Hi everyone,

For the review in JOSS  (https://github.com/openjournals/joss-reviews/issues/4840), could you check the axes used for averaging when expectation is `time_trials_tapers`, I think it should be (0, 1, 2) and not [(1, 2, 3)](https://github.com/Eden-Kramer-Lab/spectral_connectivity/blob/master/spectral_connectivity/connectivity.py#L41). Is it intentional to not mention this option in the doc of the Connectivity class?

**Comment by edeno** [comment]
Yes, that somehow snuck in. Thanks for catching that. Fixed by 5dc0b966b366c6e58bb7531486ef25d6b50d5131
