### ISSUE TITLE
Docs error for multiple-line array shapes

### ISSUE THREAD

**Issue by emilyps14** [Eden-Kramer-Lab/spectral_connectivity#47]
If the type is split across multiple lines in the docstring, the docs only pull out the first line for the "Type" section

See e.g. The `fourier_coefficients` parameter of the `Connectivity` constructor:
https://spectral-connectivity.readthedocs.io/en/latest/source/spectral_connectivity.html#spectral_connectivity.connectivity.Connectivity.expectation_type

<img width="744" alt="Screen Shot 2022-11-02 at 9 55 17 AM" src="https://user-images.githubusercontent.com/4949989/199508333-d453b80c-06ac-485e-ab9a-04e5f4bd7f06.png">

<img width="662" alt="Screen Shot 2022-11-02 at 9 56 29 AM" src="https://user-images.githubusercontent.com/4949989/199508349-4cae8718-8b5c-4f98-a1a8-6051119c11b4.png">

**Comment by edeno** [comment]
Should be fixed in the documentation.
