### ISSUE TITLE
[JOSS] Usage examples and tutorials

### ISSUE THREAD

**Issue by AJQuinn** [Eden-Kramer-Lab/spectral_connectivity#51]
Hello - I like the usage example in the main README but the tutorial jupyter notebooks are most likely only helpful for current experts. The content is good but contains very large code blocks and reads a bit like a list.

I would strongly recommend including one or two tutorials which break down the large code blocks and include a good amount of prose explaning what each chunk of code is doing and why. This doesn't need to be absolutely extensive but is hugely valuable for new users.

Some examples from similar toolboxes

- https://sails.readthedocs.io/en/stable/tutorials/tutorial5.html
- https://mne.tools/mne-connectivity/stable/auto_examples/dpli_wpli_pli.html
- https://nipy.org/nitime/examples/ar_est_2vars.html

xref: https://github.com/openjournals/joss-reviews/issues/4840

**Comment by edeno** [comment]
Got it. Agreed that there needs to be more intro to using the API and I think the simplicity of using the API is one of our strengths. I will work on the documentation website and provide more introductory tutorials.

**Comment by AJQuinn** [comment]
Great - agreed that the API is a strength, this really comes across in the README example.

**Comment by edeno** [comment]
Hi @AJQuinn , I've reworked the documentation and added a [tutorial](https://spectral-connectivity.readthedocs.io/en/latest/examples/Intro_tutorial.html). Please reopen if this doesn't match what you expected.
